import{a as g,i as c,S as p}from"./assets/vendor-Qob_5Ba8.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const u of t.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();class f{constructor(){this.searchQuery="",this.page=1,this.per_page=15}async fetchImages(){const s={method:"get",url:"https://pixabay.com/api/",params:{key:"46729875-7729b8e358007a47de817f6d1",q:`${this.searchQuery}`,image_type:"photo",orientation:"horizontal",safesearch:!0,page:`${this.page}`,per_page:`${this.per_page}`}};try{const n=(await g(s)).data;return this.incrementPage(),console.log(n),n}catch{loader.classList.replace("loader","hide"),loadMoreBtn.classList.replace("load-more","hide"),c.error({title:"Error",message:"Error! Sorry, something went wrong. This is an error!",color:"#ef4040",close:!1})}}incrementPage(){this.page+=1}resetPage(){this.page=1}resetEndOfHits(){this.endOfHits=!1}get query(){return this.searchQuery}set query(s){this.searchQuery=s}}let y=document.querySelector(".gallery");function L(a){const s=a.map(r=>`<div class="photo">
   <a class="gallery-link" href="${r.largeImageURL}">
    <img
      class="gallery-image"
      src="${r.webformatURL}"
      data-source="${r.largeImageURL}"
      alt="${r.tags}"
    />
  </a>
  <div class="info">
  <p class="info-item">Likes <span class="info-item-num">${r.likes}</span></p>
  <p class="info-item">Views <span class="info-item-num">${r.views}</span></p>
  <p class="info-item">Comments <span class="info-item-num">${r.comments}</span></p>
  <p class="info-item">Downloads <span class="info-item-num">${r.downloads}</span></p>
  </div>
     </div> `).join("");y.insertAdjacentHTML("beforeend",s)}let w=document.querySelector(".gallery");document.querySelector(".search-form-btn");let m=document.querySelector(".search-form");document.querySelector(".search-form-input");let S=new p(".gallery a"),l=document.querySelector(".loader"),o=document.querySelector(".load-more");l.classList.replace("loader","hide");o.classList.replace("load-more","hide");let d=0;const i=new f;m.addEventListener("submit",v);o.addEventListener("click",q);function v(a){if(a.preventDefault(),b(),i.query=a.currentTarget.elements.searchQuery.value.trim(),l.classList.replace("hide","loader"),o.classList.replace("load-more","hide"),i.resetPage(),i.query!==""){d=0,h(),m.reset();return}else{l.classList.replace("loader","hide"),c.warning({title:"Caution",message:"You forgot important data! Enter something!",color:"#ffa000",close:!1});return}}async function h(){o.classList.replace("load-more","hide"),await i.fetchImages().then(({hits:a,totalHits:s})=>{if(!a.length){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",color:"#ef4040",close:!1}),l.classList.replace("loader","hide"),o.classList.replace("load-more","hide");return}i.totalPage=Math.ceil(s/i.per_page),L(a);let n=document.querySelector(".gallery-image").getBoundingClientRect();window.scrollBy(0,-window.innerHeight),window.scrollBy({top:n.height*2,behavior:"smooth"}),d+=1,S.refresh(),l.classList.replace("loader","hide"),d<i.totalPage&&o.classList.replace("hide","load-more"),d>=i.totalPage&&(o.classList.replace("load-more","hide"),c.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",color:"#ef4040",close:!1}))}).catch(a=>{l.classList.replace("loader","hide"),o.classList.replace("load-more","hide"),c.error({title:"Error",message:"Error! Sorry, something went wrong. This is an error!",color:"#ef4040",close:!1})})}new p(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function b(){w.innerHTML=""}function q(){l.classList.replace("hide","loader"),l.classList.add("loader-under-btn"),o.classList.replace("load-more","hide"),h(),l.classList.remove("loader-under-btn")}
//# sourceMappingURL=index.js.map
