import{a as f,i as d,S as m}from"./assets/vendor-Qob_5Ba8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function e(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(r){if(r.ep)return;r.ep=!0;const s=e(r);fetch(r.href,s)}})();class h{constructor(){this.searchQuery="",this.page=1,this.per_page=15}async fetchImages(){const t={method:"get",url:"https://pixabay.com/api/",params:{key:"46729875-7729b8e358007a47de817f6d1",q:`${this.searchQuery}`,image_type:"photo",orientation:"horizontal",safesearch:!0,page:`${this.page}`,per_page:`${this.per_page}`}};try{const n=(await f(t)).data;return this.incrementPage(),n}catch{loader.classList.replace("loader","hide"),loadMoreBtn.classList.replace("load-more","hide"),d.error({title:"Error",message:"Error! Sorry, something went wrong. This is an error!",color:"#ef4040",close:!1})}}incrementPage(){this.page+=1}resetPage(){this.page=1}resetEndOfHits(){this.endOfHits=!1}get query(){return this.searchQuery}set query(t){this.searchQuery=t}}let g=document.querySelector(".gallery");function y(a){const t=a.map(e=>`<div class="photo">
   <a class="gallery-link" href="${e.largeImageURL}">
    <img
      class="gallery-image"
      src="${e.webformatURL}"
      data-source="${e.largeImageURL}"
      alt="${e.tags}"
    />
  </a>
  <div class="info">
  <p class="info-item">Likes <span class="info-item-num">${e.likes}</span></p>
  <p class="info-item">Views <span class="info-item-num">${e.views}</span></p>
  <p class="info-item">Comments <span class="info-item-num">${e.comments}</span></p>
  <p class="info-item">Downloads <span class="info-item-num">${e.downloads}</span></p>
  </div>
     </div> `).join("");g.insertAdjacentHTML("beforeend",t)}let L=document.querySelector(".gallery");document.querySelector(".search-form-btn");let p=document.querySelector(".search-form");document.querySelector(".search-form-input");let w=new m(".gallery a"),l=document.querySelector(".loader"),o=document.querySelector(".load-more");l.classList.replace("loader","hide");o.classList.replace("load-more","hide");let i=0;const c=new h;p.addEventListener("submit",S);function S(a){if(a.preventDefault(),$(),c.query=a.currentTarget.elements.searchQuery.value.trim(),l.classList.replace("hide","loader"),o.classList.replace("load-more","hide"),c.resetPage(),c.query!==""){i=0,q(),p.reset();return}else{l.classList.replace("loader","hide"),d.warning({title:"Caution",message:"You forgot important data! Enter something!",color:"#ffa000",close:!1});return}}async function q(){o.classList.replace("load-more","hide");const a=await c.fetchImages(),{hits:t,totalHits:e}=a;if(i+=t.length,!t.length){d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",color:"#ef4040",close:!1}),l.classList.replace("loader","hide"),o.classList.replace("load-more","hide");return}y(t),i+=t.length,w.refresh(),l.classList.replace("loader","hide"),i<e&&o.classList.replace("hide","load-more"),i>=e&&(o.classList.replace("load-more","hide"),d.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",color:"#ef4040",close:!1}))}new m(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function $(){L.innerHTML=""}
//# sourceMappingURL=index.js.map
