import{a as g,i as d,S as u}from"./assets/vendor-Qob_5Ba8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&i(m)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();class h{constructor(){this.searchQuery="",this.page=1,this.per_page=15}async fetchImages(){const t={method:"get",url:"https://pixabay.com/api/",params:{key:"46729875-7729b8e358007a47de817f6d1",q:`${this.searchQuery}`,image_type:"photo",orientation:"horizontal",safesearch:!0,page:`${this.page}`,per_page:`${this.per_page}`}};try{const i=(await g(t)).data;return this.incrementPage(),i}catch{loader.classList.replace("loader","hide"),loadMoreBtn.classList.replace("load-more","hide"),d.error({title:"Error",message:"Error! Sorry, something went wrong. This is an error!",color:"#ef4040",close:!1})}}incrementPage(){this.page+=1}resetPage(){this.page=1}resetEndOfHits(){this.endOfHits=!1}get query(){return this.searchQuery}set query(t){this.searchQuery=t}}let y=document.querySelector(".gallery");function L(a){const t=a.map(r=>`<div class="photo">
   <a class="gallery-link" href="${r.largeImageURL}">
    <img
      class="gallery-image"
      src="${r.webformatURL}"
      data-source="${r.largeImageURL}"
      alt="${r.tags}"
    />
  </a>
  <div class="info">
  <p class="info-item">Likes <span class="info-item-num">${r.likes}</span></p>
  <p class="info-item">Views <span class="info-item-num">${r.views}</span></p>
  <p class="info-item">Comments <span class="info-item-num">${r.comments}</span></p>
  <p class="info-item">Downloads <span class="info-item-num">${r.downloads}</span></p>
  </div>
     </div> `).join("");y.insertAdjacentHTML("beforeend",t)}let w=document.querySelector(".gallery");document.querySelector(".search-form-btn");let p=document.querySelector(".search-form");document.querySelector(".search-form-input");let S=new u(".gallery a"),l=document.querySelector(".loader"),o=document.querySelector(".load-more");l.classList.replace("loader","hide");o.classList.replace("load-more","hide");let n=0;const c=new h;p.addEventListener("submit",v);o.addEventListener("click",q);function v(a){if(a.preventDefault(),b(),c.query=a.currentTarget.elements.searchQuery.value.trim(),l.classList.replace("hide","loader"),o.classList.replace("load-more","hide"),c.resetPage(),c.query!==""){n=0,f(),p.reset();return}else{l.classList.replace("loader","hide"),d.warning({title:"Caution",message:"You forgot important data! Enter something!",color:"#ffa000",close:!1});return}}async function f(){o.classList.replace("load-more","hide");const a=await c.fetchImages(),{hits:t,totalHits:r}=a;if(n+=t.length,!t.length){d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",color:"#ef4040",close:!1}),l.classList.replace("loader","hide"),o.classList.replace("load-more","hide");return}L(t);let e=document.querySelector(".gallery-image").getBoundingClientRect();window.scrollBy(0,-window.innerHeight),window.scrollBy({top:e.height*2,behavior:"smooth"}),n+=t.length,S.refresh(),l.classList.replace("loader","hide"),n<r&&o.classList.replace("hide","load-more"),n>=r&&(o.classList.replace("load-more","hide"),d.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",color:"#ef4040",close:!1}))}new u(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function b(){w.innerHTML=""}function q(){c.incrementPage(),l.classList.replace("hide","loader"),l.classList.add("loader-under-btn"),o.classList.replace("load-more","hide"),f(),l.classList.remove("loader-under-btn")}
//# sourceMappingURL=index.js.map
